project_name: 'Base GRU for IC' # Ready for change
data_name: 'data_IC_15m.csv'
metadata: ['datetime', 'open', 'close', 'high', 'low', 'volume']
max_epochs: 100
experiment_name: 'not normalization for prediction' # Ready for change